<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>voss_hmi</name>
  <version>0.1.0</version>
  <description>MQTT 브리지·작업 로그</description>
  <maintainer email="team@example.com">정의석</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>voss_msgs</depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-psycopg2</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
